### ISSUE TITLE
--port argument ignored as of version 0.15.x

### ISSUE THREAD

**Issue by stevage** [mojodna/tessera#104]
This worked fine in 0.14.2.

But in 0.15.0:

```
node node_modules/tessera/bin/tessera.js --port 4001
internal/validators.js:216
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.
    at new NodeError (internal/errors.js:322:7)
    at validatePort (internal/validators.js:216:11)
    at Server.listen (net.js:1457:5)
    at Function.listen (/home/steve/work/crowdspot/schoolscape/schoolscape/node_modules/tessera/node_modules/express/lib/application.js:618:24)
    at module.exports (/home/steve/work/crowdspot/schoolscape/schoolscape/node_modules/tessera/server.js:131:20)
    at Object.<anonymous> (/home/steve/work/crowdspot/schoolscape/schoolscape/node_modules/tessera/bin/tessera.js:64:30)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_SOCKET_BAD_PORT'
}
```

Setting the PORT environment variable works:

```
PORT=4001 node node_modules/tessera/bin/tessera.js
```

**Comment by mojodna** [comment]
Thanks for spotting this. Looks like the same problem applies to other numeric options. I'll have an updated release out shortly (today).
