### ISSUE TITLE
Tessera crashes when loaded as a tile layer into CartoDB?

### ISSUE THREAD

**Issue by almccon** [mojodna/tessera#17]
I _think_ this is what's happening.

I tried to use this URL: `http://ec2-54-152-68-8.compute-1.amazonaws.com/richmond/6/34/33.png`, converting it into `http://ec2-54-152-68-8.compute-1.amazonaws.com/richmond/{z}/{x}/{y}.png` for use as a CartoDB basemap. CartoDB gives me message that it can't validate the url, but I think that's because tessera has just crashed. Tessera says this:

```
GET /richmond/0/0 404 1.629 ms - 25
GET /richmond/0/0/ 404 1.003 ms - 26
GET /richmond/0/0/%7B 404 1.504 ms - 29
GET /richmond/0/0/%7By 404 1.112 ms - 30
GET /richmond/0/0/0 404 1.045 ms - 27
GET /richmond/0/0/0. 404 1.283 ms - 28
Invalid format 'p', expected 'png'
GET /richmond/0/0/0.p 404 1.712 ms - -

crypto.js:240
  this._binding.update(data, encoding);
                ^
TypeError: Not a string or buffer
    at Hash.update (crypto.js:240:17)
    at md5sum (/home/ubuntu/src/openterrain-map/node_modules/tessera/lib/app.js:39:8)
    at /home/ubuntu/src/openterrain-map/node_modules/tessera/lib/app.js:191:38
    at Object._onImmediate (/home/ubuntu/src/openterrain-map/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:74:25)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

It looks like the 0/0/0 requests are the probing by CartoDB?

**Comment by almccon** [comment]
Update: installing the latest version of tessera doesn't have this problem!
