### ISSUE TITLE
Example config file broken?

### ISSUE THREAD

**Issue by Schwanksta** [mojodna/tessera#22]
Literally just copying and pasting the example config in the README: 

```/home/kschwen/www/tiles.schwanksta.com/project/tess.config:2
  "/": {
     ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/lib/node_modules/tessera/server.js:61:18)
    at Object.<anonymous> (/usr/lib/node_modules/tessera/bin/tessera.js:70:30)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by Schwanksta** [comment]
My bad, if the file isn't a .json extension this will happen.
