### ISSUE TITLE
Cannot accept empty buffer as protobuf

### ISSUE THREAD

**Issue by flemmens** [mojodna/tessera#35]
I got this error message with the last v0.6 version when I zoom on some parts of my map:

/usr/local/lib/node_modules/tilelive-merge/index.js:129
            vt.setData(buf);
               ^
Error: cannot accept empty buffer as protobuf
    at Error (native)
    at /usr/local/lib/node_modules/tilelive-merge/index.js:129:16
    at fn (/usr/local/lib/node_modules/tilelive-merge/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/tilelive-merge/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by mojodna** [comment]
Moved to `tilelive-merge`: https://github.com/mojodna/tilelive-merge/issues/4
