### ISSUE TITLE
Server.js is missing from NPM package

### ISSUE THREAD

**Issue by hannesj** [mojodna/tessera#40]
For some reason server.js is not bundled in http://registry.npmjs.org/tessera/-/tessera-0.7.0.tgz

This causes the following issue when trying to run:

```
data:    node_modules/tessera/bin/tessera.js:37 - module.js:340
data:    node_modules/tessera/bin/tessera.js:37 -     throw err;
data:    node_modules/tessera/bin/tessera.js:37 -     ^
data:    node_modules/tessera/bin/tessera.js:37 - Error: Cannot find module '../server'
data:    node_modules/tessera/bin/tessera.js:37 -     at Function.Module._resolveFilename (module.js:338:15)
data:    node_modules/tessera/bin/tessera.js:37 -     at Function.Module._load (module.js:289:25)
data:    node_modules/tessera/bin/tessera.js:37 -     at Module.require (module.js:366:17)
data:    node_modules/tessera/bin/tessera.js:37 -     at require (module.js:385:17)
data:    node_modules/tessera/bin/tessera.js:37 -     at Object.<anonymous> (/home/reittiopas/docker/map-server/node_modules/tessera/bin/tessera.js:70:10)
data:    node_modules/tessera/bin/tessera.js:37 -     at Module._compile (module.js:435:26)
data:    node_modules/tessera/bin/tessera.js:37 -     at Object.Module._extensions..js (module.js:442:10)
data:    node_modules/tessera/bin/tessera.js:37 -     at Module.load (module.js:356:32)
data:    node_modules/tessera/bin/tessera.js:37 -     at Function.Module._load (module.js:313:12)
data:    node_modules/tessera/bin/tessera.js:37 -     at Function.Module.runMain (module.js:467:10)
```

**Comment by mojodna** [comment]
Totally weird! I didn't do anything different to publish. In any case, I just pushed v0.7.1 and confirmed that it's present.

Thanks!

**Comment by hannesj** [comment]
Thanks, works now!
